version: '3.8'

services:
  backend:
    build:
      context: ./backend
      target: development
    environment:
      NODE_ENV: test
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: test_db
      DB_USER: test
      DB_PASSWORD: test
      DB_SYNC: 'true'
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: test_jwt_secret
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run test:watch

  frontend:
    build:
      context: ./frontend
      target: development
    environment:
      NODE_ENV: test
      VITE_API_URL: http://localhost:3000/api
    ports:
      - '3001:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run test:watch
    depends_on:
      - backend

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d test_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:6-alpine
    ports:
      - '6379:6379'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
