# Netlify configuration for BulkMail

[build]
  # Install dependencies and build the frontend
  command = "cd frontend && npm install && npm run build"
  
  # The directory that contains the built frontend assets
  publish = "frontend/dist"
  
  # The directory where Netlify will look for serverless functions
  functions = "functions"

  # Environment variables for build process
  [build.environment]
    # Node.js version
    NODE_VERSION = "18"
    
    # Enable Node.js modules
    NPM_FLAGS = "--legacy-peer-deps"
    
    # Build time environment variables
    VITE_API_URL = "/api"
    NODE_ENV = "production"

# Redirects and rewrites rules
[[redirects]]
  # Proxy all API requests to our serverless function
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# SPA fallback - redirect all other requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:;"
    
    # CORS headers for API
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Cache control for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache control for HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Cache control for other files
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=600"
